[WIP] Feature/appc credits contract
AppStoreFoundation/asf-contracts pull request #107
Opened 2018-11-22 17:38 UTC by GustavoRSSilva

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Checklist:

- [ ] You have followed our [**contributing guidelines**](https://github.com/AppStoreFoundation/asf-contracts/wiki/Contributing-to-AppCoins-Protocol-smart-contracts)
- [ ] double-check your branch is based on `dev` and targets `dev` 
- [ ] Pull request has tests (at least 80% coverage)
- [ ] Code is well-commented, linted and follows project conventions
- [ ] Documentation is updated (if necessary)
- [ ] Description explains the issue/use-case resolved and auto-closes related issues

2018-11-23 10:46 UTC, tcrosado requested changes

2018-11-23 10:46 UTC, tcrosado commented on contracts/AppCoinsCreditsBalance.sol
> +    function getBbalanceProof() public view returns(bytes) {
I think this is a typo

2018-11-23 10:46 UTC, tcrosado commented on contracts/AppCoinsCreditsBalance.sol
> +    function registerBalanceProof(bytes _merkleTreeHash)
This function should have some documentation

2018-11-23 10:46 UTC, tcrosado commented on contracts/AppCoinsCreditsBalance.sol
> +    function depositFunds(uint _amount)
Talking with @zepcp, registerBalanceProof can be an internal function called when depositFunds and withdrawFunds functions are called

2018-11-23 15:06 UTC, tcrosado approved these changes

2018-11-23 16:23 UTC, DioPires commented on contracts/Advertisement.sol
>              uint[] vercodes
#### Tests:
```diff 
+ 112 passing
```
#### Test coverage: 
82.97 %

2018-11-23 17:40 UTC, DioPires commented on contracts/Advertisement.sol
>              uint[] vercodes
#### Tests:
```diff 
+ 112 passing
```
#### Test coverage: 
82.97 %

2018-11-23 17:50 UTC, DioPires commented on contracts/Advertisement.sol
>              uint[] vercodes
#### Tests:
```diff 
+ 112 passing
```
#### Test coverage: 
82.97 %

2018-11-27 17:27 UTC, DioPires commented on contracts/Advertisement.sol
>              uint[] vercodes
#### Tests:
```diff 
+ 112 passing
```
#### Test coverage: 
82.97 %

2018-11-27 17:37 UTC, DioPires commented on contracts/Advertisement.sol
>              uint[] vercodes
#### Tests:
```diff 
+ 112 passing
```
#### Test coverage: 
82.97 %

2018-11-29 09:58 UTC, DioPires approved these changes

2018-11-29 09:58 UTC, merged

2019-02-07 11:13 UTC, tcrosado commented
:tada: This PR is included in version 2.1.0 :tada:

The release is available on [GitHub release](https://github.com/AppStoreFoundation/asf-contracts/releases/tag/v2.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: