Docs/security policy
AppStoreFoundation/asf-contracts pull request #108
Opened 2018-11-28 10:34 UTC by tcrosado

## Description
Security policy required to run a bug bounty on HackerOne

## Motivation and Context
Improve contract security
Strictly define rules for vulnerability reporting

## How Has This Been Tested?

## Screenshots (if appropriate):

## Checklist:

- [x] You have followed our [**contributing guidelines**](https://github.com/AppStoreFoundation/asf-contracts/wiki/Contributing-to-AppCoins-Protocol-smart-contracts)
- [ ] double-check your branch is based on `dev` and targets `dev` 
- [x] Pull request has tests (at least 80% coverage)
- [x] Code is well-commented, linted and follows project conventions
- [ ] Documentation is updated (if necessary)
- [x] Description explains the issue/use-case resolved and auto-closes related issues

2018-11-28 10:39 UTC, GustavoRSSilva approved these changes

2018-11-28 10:44 UTC, DioPires commented on SECURITY.md
> +## Vulnerability Disclosure policy
#### Tests:
```diff 
+ 110 passing
```
#### Test coverage: 
82.44 %

2018-11-28 10:54 UTC, DioPires commented on SECURITY.md
> +## Vulnerability Disclosure policy
#### Tests:
```diff 
+ 110 passing
```
#### Test coverage: 
82.44 %

2018-11-28 18:26 UTC, DioPires commented on SECURITY.md
> +## Vulnerability Disclosure policy
#### Tests:
```diff 
+ 110 passing
```
#### Test coverage: 
82.44 %

2018-11-28 18:36 UTC, DioPires commented on SECURITY.md
> +## Vulnerability Disclosure policy
#### Tests:
```diff 
+ 110 passing
```
#### Test coverage: 
82.44 %

2018-11-29 10:08 UTC, DioPires commented on SECURITY.md
> +## Vulnerability Disclosure policy
#### Tests:
```diff 
+ 110 passing
```
#### Test coverage: 
82.44 %

2018-11-29 10:18 UTC, DioPires commented on SECURITY.md
> +## Vulnerability Disclosure policy
#### Tests:
```diff 
+ 110 passing
```
#### Test coverage: 
82.44 %

2018-11-29 10:28 UTC, DioPires commented on SECURITY.md
> +## Vulnerability Disclosure policy
#### Tests:
```diff 
+ 110 passing
```
#### Test coverage: 
82.44 %

2018-11-29 10:44 UTC, DioPires requested changes

2018-11-29 10:44 UTC, DioPires commented on SECURITY.md
> +### Eligibiliy and Responsible Disclosure
Should be `Eligibility`

2018-11-29 11:16 UTC, DioPires approved these changes

2018-11-29 11:17 UTC, merged

2018-11-29 11:21 UTC, DioPires commented on SECURITY.md
> +## Vulnerability Disclosure policy
#### Tests:
```diff 
+ 110 passing
```
#### Test coverage: 
82.44 %

2019-02-07 11:12 UTC, tcrosado commented
:tada: This PR is included in version 2.1.0 :tada:

The release is available on [GitHub release](https://github.com/AppStoreFoundation/asf-contracts/releases/tag/v2.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: