[new] removed entropy
AppStoreFoundation/asf-contracts pull request #110
Opened 2018-12-06 10:12 UTC by GustavoRSSilva

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Checklist:

- [ ] You have followed our [**contributing guidelines**](https://github.com/AppStoreFoundation/asf-contracts/wiki/Contributing-to-AppCoins-Protocol-smart-contracts)
- [ ] double-check your branch is based on `dev` and targets `dev` 
- [ ] Pull request has tests (at least 80% coverage)
- [ ] Code is well-commented, linted and follows project conventions
- [ ] Documentation is updated (if necessary)
- [ ] Description explains the issue/use-case resolved and auto-closes related issues

2018-12-06 10:23 UTC, DioPires commented on contracts/ExtendedAdvertisement.sol
>          onlyIfWhitelisted("createCampaign",msg.sender)
#### Tests:
```diff 
- 1 failing
```
```diff 
+ 111 passing
```
#### Test coverage: 
82.83 %

2018-12-06 10:33 UTC, DioPires commented on contracts/ExtendedAdvertisement.sol
>          onlyIfWhitelisted("createCampaign",msg.sender)
#### Tests:
```diff 
+ 111 passing
```
#### Test coverage: 
82.83 %

2018-12-06 11:09 UTC, DioPires commented on contracts/ExtendedAdvertisement.sol
>          onlyIfWhitelisted("createCampaign",msg.sender)
#### Tests:
```diff 
+ 111 passing
```
#### Test coverage: 
82.83 %

2018-12-06 11:20 UTC, DioPires commented on contracts/ExtendedAdvertisement.sol
>          onlyIfWhitelisted("createCampaign",msg.sender)
#### Tests:
```diff 
+ 111 passing
```
#### Test coverage: 
82.83 %

2018-12-10 12:08 UTC, DioPires commented on contracts/ExtendedAdvertisement.sol
>          onlyIfWhitelisted("createCampaign",msg.sender)
#### Tests:
```diff 
+ 111 passing
```
#### Test coverage: 
82.83 %

2018-12-10 12:18 UTC, DioPires commented on contracts/ExtendedAdvertisement.sol
>          onlyIfWhitelisted("createCampaign",msg.sender)
#### Tests:
```diff 
+ 111 passing
```
#### Test coverage: 
82.83 %

2018-12-24 16:04 UTC, DioPires commented on contracts/ExtendedAdvertisement.sol
>          onlyIfWhitelisted("createCampaign",msg.sender)
#### Tests:
```diff 
+ 111 passing
```
#### Test coverage: 
82.83 %

2018-12-24 16:14 UTC, DioPires commented on contracts/ExtendedAdvertisement.sol
>          onlyIfWhitelisted("createCampaign",msg.sender)
#### Tests:
```diff 
+ 111 passing
```
#### Test coverage: 
82.83 %

2018-12-28 16:06 UTC, DioPires commented on contracts/ExtendedAdvertisement.sol
>          onlyIfWhitelisted("createCampaign",msg.sender)
#### Tests:
```diff 
+ 111 passing
```
#### Test coverage: 
82.83 %

2018-12-28 16:16 UTC, DioPires commented on contracts/ExtendedAdvertisement.sol
>          onlyIfWhitelisted("createCampaign",msg.sender)
#### Tests:
```diff 
+ 111 passing
```
#### Test coverage: 
82.83 %

2019-01-02 10:33 UTC, DioPires commented on .env.example
>  EXTENDED_ADVERTISEMENT_STORAGE_KOVAN_ADDRESS=address_extended_advertisement_storage_kovan
#### Tests:
```diff 
+ 115 passing
```
#### Test coverage: 
83.64 %

2019-01-02 10:43 UTC, DioPires commented on .env.example
>  EXTENDED_ADVERTISEMENT_STORAGE_KOVAN_ADDRESS=address_extended_advertisement_storage_kovan
#### Tests:
```diff 
+ 115 passing
```
#### Test coverage: 
83.64 %

2019-01-02 11:04 UTC, tcrosado requested changes

2019-01-02 11:04 UTC, tcrosado commented on contracts/ExtendedAdvertisement.sol
> +    function registerPoA(bytes32 _bidId,bytes _timestampAndHash, bytes _signature)
We aren't using this feature. We should delete this function.

2019-01-02 11:04 UTC, tcrosado commented on test/ExtendedAdvertisementStorage.js
> +            bidIdCreation,
Why are we using this variable instead of testCampaign.bidId? 
It becomes inconsistent as we always go for testCampaign properties when using bidIdCreation variable.

2019-01-02 11:04 UTC, tcrosado commented on test/extendedAdvertisement.js
> +  		await addInstance.createCampaign(packageName,countryList,[1,2],campaignPrice,campaignPrice,startDate,endDate, accounts[8],"appcoins.io");
We could assign accounts[8] and "appcoins.io" to variables. But that's not mandatory.

2019-01-02 11:32 UTC, appcoinsteam commented on .env.example
>  EXTENDED_ADVERTISEMENT_STORAGE_KOVAN_ADDRESS=address_extended_advertisement_storage_kovan
#### Tests:
```diff 
+ 115 passing
```
#### Test coverage: 
83.64 %

2019-01-02 12:22 UTC, appcoinsteam commented on .env.example
>  EXTENDED_ADVERTISEMENT_STORAGE_KOVAN_ADDRESS=address_extended_advertisement_storage_kovan
#### Tests:
```diff 
+ 114 passing
```
#### Test coverage: 
83.97 %

2019-01-02 12:32 UTC, appcoinsteam commented on .env.example
>  EXTENDED_ADVERTISEMENT_STORAGE_KOVAN_ADDRESS=address_extended_advertisement_storage_kovan
#### Tests:
```diff 
+ 114 passing
```
#### Test coverage: 
83.97 %

2019-01-02 14:49 UTC, GustavoRSSilva commented on test/ExtendedAdvertisementStorage.js
> +            bidIdCreation,
Fixed.

2019-01-02 15:19 UTC, appcoinsteam commented on .env.example
>  EXTENDED_ADVERTISEMENT_STORAGE_KOVAN_ADDRESS=address_extended_advertisement_storage_kovan
#### Tests:
```diff 
+ 114 passing
```
#### Test coverage: 
83.97 %

2019-01-03 10:21 UTC, appcoinsteam commented on .env.example
>  EXTENDED_ADVERTISEMENT_STORAGE_KOVAN_ADDRESS=address_extended_advertisement_storage_kovan
das

2019-01-03 11:22 UTC, appcoinsteam commented on .env.example
>  EXTENDED_ADVERTISEMENT_STORAGE_KOVAN_ADDRESS=address_extended_advertisement_storage_kovan
#### Tests:
```diff 
+ 114 passing
```
#### Test coverage: 
83.97 %

2019-01-03 11:47 UTC, appcoinsteam commented on .env.example
>  EXTENDED_ADVERTISEMENT_STORAGE_KOVAN_ADDRESS=address_extended_advertisement_storage_kovan
#### Tests:
```diff 
+ 114 passing
```
#### Test coverage: 
83.97 %

2019-01-03 12:38 UTC, tcrosado approved these changes

2019-01-03 15:06 UTC, merged

2019-02-07 11:12 UTC, tcrosado commented
:tada: This PR is included in version 2.1.0 :tada:

The release is available on [GitHub release](https://github.com/AppStoreFoundation/asf-contracts/releases/tag/v2.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: