[new] added the extended advertisement contracts
AppStoreFoundation/asf-contracts pull request #94
Opened 2018-10-15 09:58 UTC by GustavoRSSilva

## AppCoins Protocol smart contracts

Thank you for contributing! Please take a moment to review our [**contributing guidelines**](https://github.com/AppStoreFoundation/asf-contracts/wiki/Contributing-to-AppCoins-Protocol-smart-contracts)
to make the process easy and effective for everyone involved.

**Please open an issue** before embarking on any significant pull request, otherwise you risk spending a lot of time working
on something that might not end up being merged into the project.

Before opening a pull request, please ensure:

- [ ] You have followed our [**contributing guidelines**](https://github.com/AppStoreFoundation/asf-contracts/wiki/Contributing-to-AppCoins-Protocol-smart-contracts)
- [ ] double-check your branch is based on `dev` and targets `dev` 
- [ ] Pull request has tests (at least 80% coverage)
- [ ] Code is well-commented, linted and follows project conventions
- [ ] Documentation is updated (if necessary)
- [ ] Description explains the issue/use-case resolved and auto-closes related issues

Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)

**IMPORTANT**: By submitting a patch, you agree to allow the project
owners to license your work under the terms of the [GPL-3.0 License](https://github.com/AppStoreFoundation/asf-contracts/blob/master/LICENSE).

2018-10-15 10:08 UTC, DioPires commented on scripts/extended-advertisement-storage-finance.js
> +const ExtendedAdvertisementStorage = artifacts.require("./ExtendedAdvertisementStorage.sol");
#### Tests:
```diff 
- 4 failing
```
```diff 
+ 100 passing
```
#### Test coverage: 
81.44 %

2018-10-15 10:15 UTC, tcrosado requested changes

2018-10-15 10:15 UTC, tcrosado commented on scripts/extended-advertisement-storage-finance.js
> +            extendedFinanceInstance = ExtendedExtendedAdvertisementFinance.at(process.env.EXTENDED_ADVERTISEMENT_FINANCE_DEVELOPMENT_ADDRESS);
I think there is a typo in this  two lines

2018-10-15 10:15 UTC, tcrosado commented on scripts/extended-advertisement-storage-finance.js
> +        extendedFinanceInstance.setAdsStorageAddress(newAdvertisementAddress).then(function(error, success) {
Shouldn't this variable be a newAdvertisementStorageAddress instead?

2018-10-15 10:17 UTC, DioPires commented on scripts/extended-advertisement-storage-finance.js
> +const ExtendedAdvertisementStorage = artifacts.require("./ExtendedAdvertisementStorage.sol");
#### Tests:
```diff 
- 4 failing
```
```diff 
+ 100 passing
```
#### Test coverage: 
81.44 %

2018-10-15 13:54 UTC, DioPires commented on scripts/extended-advertisement-storage-finance.js
> +const ExtendedAdvertisementStorage = artifacts.require("./ExtendedAdvertisementStorage.sol");
#### Tests:
```diff 
- 4 failing
```
```diff 
+ 100 passing
```
#### Test coverage: 
81.44 %

2018-10-15 14:04 UTC, DioPires commented on scripts/extended-advertisement-storage-finance.js
> +const ExtendedAdvertisementStorage = artifacts.require("./ExtendedAdvertisementStorage.sol");
#### Tests:
```diff 
- 4 failing
```
```diff 
+ 100 passing
```
#### Test coverage: 
81.44 %

2018-10-16 10:23 UTC, DioPires commented on scripts/extended-advertisement-storage-finance.js
> +const ExtendedAdvertisementStorage = artifacts.require("./ExtendedAdvertisementStorage.sol");
#### Tests:
```diff 
- 4 failing
```
```diff 
+ 100 passing
```
#### Test coverage: 
81.44 %

2018-10-16 10:31 UTC, tcrosado approved these changes

2018-10-16 10:31 UTC, merged

2018-10-16 10:33 UTC, DioPires commented on scripts/extended-advertisement-storage-finance.js
> +const ExtendedAdvertisementStorage = artifacts.require("./ExtendedAdvertisementStorage.sol");
#### Tests:
```diff 
- 4 failing
```
```diff 
+ 100 passing
```
#### Test coverage: 
81.44 %

2018-10-25 10:52 UTC, tcrosado commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on [GitHub release](https://github.com/AppStoreFoundation/asf-contracts/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: